name: "GitHub Workflow Dispatcher"
description: "Send workflow_dispatch event"
branding:
  icon: "send"
  color: "green"
inputs:
  repository:
    description: "Target repository"
    default: ${{ github.repository }}
  workflow:
    description: "Workflow ID or filename"
  ref:
    description: "Workflow ref"
    default: ${{ github.ref }}
  inputs:
    description: "Workflow inputs"
  token:
    description: "GitHub token"
  default-token:
    description: "Default GitHub token"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
