name: "Workflow Dispatch"
description: "Trigger workflow_dispatch event"
branding:
  icon: "send"
  color: "green"
inputs:
  repository:
    description: "Target repository"
    default: ${{ github.repository }}
  workflow:
    description: "Workflow ID or filename"
    required: true
  ref:
    description: "Workflow ref"
  inputs:
    description: "Workflow inputs"
  token:
    description: "GitHub token"
  default-token:
    description: "Default GitHub token"
    default: ${{ github.token }}
runs:
  using: "node16"
  main: "dist/index.js"
